WebcajaBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: WebcajaBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        nameEs:
            type: string
            length: 255
            nullable: true
            column: name_es
        unit:
            type: integer
        code:
            type: string
            length: 255
        stock:
            type: integer
            nullable: true
        price:
            type: float
        description:
            type: string
            length: 255
            nullable: true
        foto:
            type: string
            length: 255
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
