WebcajaBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: WebcajaBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        cart:
            targetEntity: Cart
            mappedBy: user
    oneToMany:
        orderInfos:
            targetEntity: OrderInfo
            mappedBy: user
    lifecycleCallbacks: {  }
