webcaja_carrito:
    path:     /
    defaults: { _controller: "WebcajaBundle:Carrito:carrito" }

webcaja_addToCarrito:
    path:     /addToCarrito/{id}
    defaults: { _controller: "WebcajaBundle:Carrito:addToCarrito" }

webcaja_clearCarrito:
    path:     /clearCarrito
    defaults: { _controller: "WebcajaBundle:Carrito:clearCarrito" }

webcaja_ajaxCarrito:
    path:     /ajaxUpdate
    defaults: { _controller: "WebcajaBundle:Carrito:ajaxUpdate" }

webcaja_addtocartAjax:
    path:     /addtocartAjax
    defaults: { _controller: "WebcajaBundle:Carrito:addtocartAjax" }